# Exported from Render on 2024-09-24T20:57:04Z
services:
- type: web
  name: mysite
  runtime: ruby
  repo: https://github.com/mauricio-chirino/mysite
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./bin/render-build.sh
  startCommand: bundle exec rails server
version: "1"
